load("@rules_license//rules:license_kind.bzl", "license_kind")

package(
    default_visibility = ["//visibility:public"],
)

license_kind(
    name = "BSL-1.0",
    conditions = [],
    url = "https://spdx.org/licenses/BSL-1.0.html",
)
